// All copy and figures are taken from bajkamalsingh.me; structure and
// presentation are original to this rebuild.

const A = (p) => `${import.meta.env.BASE_URL}assets/${p}`;
export const asset = A;

export const person = {
  name: 'Bajkamal Singh',
  alias: 'Baaz',
  city: 'Delhi, India',
  school: "SRCC '27",
  email: 'bajkamalsingh1@gmail.com',
  mailSubject: "Internship? You're hired. (Almost.)",
  mailBody:
    'Hey Bajkamal,\n\nCame here to check a portfolio.\nLeft with a mild urge to hire you.\n\nLet’s talk before someone else hires you.',
  instagram: 'https://www.instagram.com/bajkamal07/',
  linkedin: 'https://www.linkedin.com/in/bajkamalsingh/',
  roles: ['Designer', 'Artist Manager', 'Creative Director'],
};

// The night shift: each chapter owns a slice of the clock.
export const chapters = [
  { id: 'hero', time: '20:00', label: 'Clock in' },
  { id: 'origin', time: '21:30', label: 'Origin' },
  { id: 'hustle', time: '23:00', label: 'Hustle' },
  { id: 'cases', time: '00:30', label: 'Best work' },
  { id: 'wall', time: '02:45', label: 'Insomniac work' },
  { id: 'contact', time: '05:30', label: 'Clock out' },
];

export const highlights = [
  { value: 186, suffix: 'M+', label: 'views driven', note: 'in 3 months' },
  { value: 33, suffix: 'M+', label: 'campaign reach', note: 'flagship brand events' },
  { value: 40, suffix: '+', label: 'live standup shows', note: 'scaled nationwide in 3 months' },
  { value: 1, prefix: 'Rank ', label: 'DU, 5 subjects', note: 'gotta keep parents happy' },
];

export const internships = [
  {
    company: 'Grimbyte Technologies',
    desc: 'Consulting firm specialising in marketing transformation & GTM strategies',
    duration: '4 Weeks',
    role: 'Brand Strategy Intern',
    points: [
      'Configured <b>GA4, Meta & SEMrush dashboards</b> for 6+ clients — replaced vanity metrics with performance KPIs to validate marketing spend and optimise budget allocation.',
      'Mapped <b>CX journeys for 4 clients</b> to identify friction points & optimise user flows, reducing drop-off rates & manual touchpoints while improving lead capture.',
    ],
    stats: [['6+', 'Clients'], ['4', 'CX journeys mapped'], ['3', 'Tools deployed']],
  },
  {
    company: 'Blue Tea',
    desc: "India's leading herbal tea brand, featured on Shark Tank India, with 1M+ global customers",
    duration: '4 Weeks',
    role: 'Live Project Associate',
    points: [
      'Executed a targeted <b>offline activation strategy</b>, securing 5+ strategic B2B partnerships to distribute 2,000+ units into high-value customer segments.',
      'Architected an <b>influencer campaign model</b>, managing outreach to 90+ creators and achieving ₹0.10 CPV — outperforming industry benchmarks.',
    ],
    stats: [['90+', 'Creators reached'], ['₹0.10', 'CPV achieved'], ['2K+', 'Units distributed']],
  },
  {
    company: 'Dr. Water',
    desc: 'Global US-based brand delivering premium hydrogen hydration solutions',
    duration: '8 Weeks',
    role: 'Project Head',
    points: [
      'Identified <b>6 key customer personas</b> through primary & secondary research, analysing 200+ responses & behavioural patterns to frame 360° marketing strategies.',
      'Benchmarked <b>18+ hydration brands</b>, defining competitive gaps and synthesising 2,000+ data points into targeted marketing strategy.',
    ],
    stats: [['6', 'Personas mapped'], ['2K+', 'Data points'], ['18+', 'Brands benchmarked']],
  },
  {
    company: 'Frost & Sullivan',
    desc: 'International consulting firm specialising in market research & strategic advisory',
    duration: '4 Weeks',
    role: 'Live Project Associate',
    points: [
      'Benchmarked advancements in <b>six mobility domains</b>, identifying synergies projected to unlock ₹42,000 crore+ in combined market opportunities.',
      'Evaluated & ranked <b>200+ technologies</b> using the Mobility Innovation Scoring Model, surfacing the top 10 innovations for strategic client focus.',
    ],
    stats: [['200+', 'Tech ranked'], ['₹42K Cr+', 'Market opportunity'], ['6', 'Mobility domains']],
  },
];

export const cases = [
  {
    id: 'krishna',
    no: '01',
    title: 'Krishna Shukla',
    client: 'Krishna Shukla',
    role: 'Freelance · Brand & Business Manager',
    sub: 'Stand-up artist, Delhi · 130K+ Instagram followers',
    tags: ['Content Strategy', 'Creator Economy', 'Touring Business'],
    stat: ['₹4.4L', 'revenue'],
    theme: { bg: '#F1ECE2', fg: '#051024', accent: '#0A2BF5' },
    cover: A('work/ksm1.webp'),
    problem: {
      kicker: 'The problem',
      head: '186M views. Zero revenue infrastructure.',
      body: "The attention existed. The business didn't.",
      list: ['Trapped in a local echo chamber', 'Passive viewers who rarely shared', 'Limited to unscalable, ad-hoc college gigs'],
    },
    moves: [
      ['Identity-based content', 'Shifted to highly relatable, POV-driven identity content to acquire cold audiences aggressively.'],
      ['Virality engine', 'Achieved a <b>3x loop rate</b> & <b>1:3 share-to-like</b> — turning viewers into distributors.'],
      ['Touring IP', 'Operationalised <b>40+ shows</b> across Delhi, Jaipur, Lucknow & Goa with repeatable logistics.'],
    ],
    metrics: [
      ['186M+', 'Views', '54M+ accounts reached'],
      ['100K+', 'Followers', '115% growth in 3 months'],
      ['46%', 'Engagement rate', '30% above industry avg'],
      ['₹4L+', 'Standup revenue', '₹40K+ brand partnerships'],
      ['3X', 'Loop rate', '1:3 shares to likes'],
      ['40+', 'Shows pan-India', 'Jaipur, Kanpur, Lucknow, Gurugram'],
    ],
    gallery: [
      [A('work/ksm1.webp'), 'Instagram insights: 186,309,364 views over 90 days'],
      [A('work/ksm2.webp'), 'Platform analytics screen'],
      [A('work/ksm3.webp'), 'Platform analytics screen'],
    ],
    galleryStyle: 'phones',
  },
  {
    id: 'rntl',
    no: '02',
    title: 'RNTL.',
    client: 'RNTL.',
    logo: A('brand/rntl.webp'),
    role: 'Founding Marketer · Core Team',
    sub: 'Fashion rental marketplace for Gen-Z',
    tags: ['Meta Ads', 'Consumer Psychology', 'Brand Launch'],
    stat: ['4.6X', 'efficiency lift'],
    theme: { bg: '#8A9ED8', fg: '#051024', accent: '#F1ECE2' },
    cover: A('work/ep3.webp'),
    problem: {
      kicker: 'Consumer fear',
      head: '“Why rent when I can own?”',
      body: 'Renting felt like a sunk cost. No social proof, no category trust, zero brand history. The “is this brand real?” question came before any purchase intent.',
    },
    answer: {
      kicker: 'Our answer',
      head: 'Borrowed equity. Sell the lifestyle, not the product.',
      body: 'Made credible people endorse renting as a lifestyle — removing the trust deficit before it was even asked.',
    },
    episodes: [
      ['Nikita Luther', '95K+ · Winner, Traitors', A('work/ep1.webp')],
      ['Harpriya Bains', '215K+ · Stand-up comedian', A('work/ep2.webp')],
      ['Anya Singh', '496K+ · Actress, Stree 2', A('work/ep3.webp')],
      ['Ranjit Bajaj', '1.1M+ · Owner, Minerva FC', A('work/ep4.webp')],
      ['Rajat Barmecha', '87K+ · Actor, Udaan', A('work/ep5.webp')],
    ],
    episodesNote: '5 industry voices · 2M+ combined network',
    moves: [
      ['Legitimacy, day one', 'Positioned RNTL as a legitimate industry player from Day 1.'],
      ['Narrative flow', 'Defined flow & interaction convo for narrative consistency.'],
      ['Trust transfer', 'Removed the “is this brand trustable?” fear via borrowed equity, with planned Q&A and SKU integration to endorse renting.'],
    ],
    pilot: {
      head: 'Meta pilot run — catalog + personality-led launch',
      body: 'A micro-budget pilot to validate acquisition channels for Gen-Z fashion rentals. Social proof surfaced as the core trust lever: pivoting from catalog-only ads to personality-led Reels delivered a <b>4.6x efficiency lift</b>.',
      phases: [
        ['Phase 01', 'Catalog ad set', A('work/catalog_grid.webp')],
        ['Phase 02', 'Personality-led', A('work/personality_grid.webp')],
      ],
    },
    metrics: [
      ['35%+', 'Hook rate', 'Benchmark 20–25%'],
      ['₹18.4', 'Cost per messaging conversation', '@4K impressions'],
      ['25–50%', 'Lower CPC', 'vs industry average'],
    ],
    gallery: [
      [A('work/metachart.webp'), 'Meta ads performance chart'],
      [A('work/ad_breakup.webp'), 'Ad breakup analysis — creative anatomy of the winning asset'],
    ],
    link: ['Full teardown on LinkedIn', 'https://linkedin.com/posts/bajkamalsingh_marketing-strategy-consumerbehaviour-activity-7419962873264734208-qPWS'],
  },
  {
    id: 'sins',
    no: '03',
    title: 'Sins Crew',
    client: 'Sinskari',
    logo: A('brand/sinskari.webp'),
    role: 'Strategy Intern · 4 Weeks',
    sub: 'Sinskari — growing D2C streetwear brand for Gen-Z India',
    tags: ['Email Automation', 'CX Journey', 'Retention'],
    stat: ['25+', 'carts recovered'],
    theme: { bg: '#0A2BF5', fg: '#F1ECE2', accent: '#E8FF3A' },
    problem: {
      kicker: 'The leak',
      head: 'No behavioural triggers. No segment logic. No recovery sequences.',
      body: 'Revenue was bleeding through abandoned carts daily — with zero infrastructure to catch it.',
    },
    funnel: {
      entry: ['New customer', 'Registration / sign-up', 'T+0 · Welcome email + brand story + most-loved products'],
      lanes: [
        {
          when: 'Left the site',
          steps: [['T+24H', '“Someone in your city just bought X” — location-based trigger']],
          exit: 'Move to old-customer sequence',
        },
        {
          when: "Browsed, didn't add",
          steps: [
            ['B+2H', '“You forgot me, but I am still thinking about you” + styling moodboard'],
            ['B+24H', 'Hot-selling / vibe creative + free delivery for 24H'],
          ],
          exit: 'Campaign exits',
        },
        {
          when: 'Added & checked out',
          steps: [
            ['D+0', 'Elite-taste validation + receipt + tracking'],
            ['E+48H', 'Fit check + feedback + Instagram story push'],
            ['E+20D', 'Recommendation matching the item'],
            ['E+25D', '10% off + 50+20 credits, 12-hour countdown'],
          ],
          exit: 'Move to old-customer sequence',
        },
        {
          when: "Added, didn't check out",
          steps: [
            ['C+1H', '“I guess your crush texted you, that’s why you left me on seen”'],
            ['C+24H', '10% off + 50 credits, 12-hour countdown'],
            ['C+48H', '“Your bag is about to be stolen” in the next 2 hours'],
          ],
          exit: 'Checked out → purchase sequence · else exit',
        },
      ],
    },
    metrics: [
      ['25+', 'Carts recovered', 'Direct revenue save'],
      ['10%', 'Conversion boost', 'Site-wide lift'],
      ['15%', 'Traffic increase', 'Return sessions'],
      ['10%', 'Drop-off reduced', 'Funnel optimisation'],
    ],
  },
  {
    id: 'histrionica',
    no: '04',
    title: 'Histrionica',
    client: 'Dramsoc SRCC',
    logo: A('brand/dram.webp'),
    role: 'Vice President · The Dramatics Society, SRCC',
    sub: "DU's most-followed college society · Tier-1 flagship annual festival",
    tags: ['Sponsorships', 'Performance Marketing', 'Creative Direction'],
    stat: ['₹55L+', 'secured'],
    theme: { bg: '#121212', fg: '#F1ECE2', accent: '#F5C518' },
    cover: A('work/tds1.webp'),
    problem: {
      kicker: 'Starting point',
      head: "One of DU's oldest societies had no systematic growth engine.",
      body: 'Sponsorships were ad-hoc. Digital presence minimal. No playbook for brand partnerships or content at scale.',
    },
    metrics: [
      ['₹55L+', 'Sponsorship value', 'secured'],
      ['33M+', 'Campaign reach', 'total'],
      ['234%', 'YoY growth', ''],
      ['12K+', 'Event footfall', 'total'],
    ],
    moves: [
      ['Sponsorship strategy', "Swiggy, Rapido, McDonald's, Redtape, Zebronics. Negotiated & closed ₹55L+ in brand deals. Managed 30+ sponsors for JFL."],
      ['Performance marketing', '2.2M+ reach in under 3 days. 837K incremental boost. 96.4% ↑ unique visitors. 283K interactions via ad spend.'],
      ['Creative direction', 'A/B tested across 6+ locations. Directed every static & reel asset to create FOMO and drive engagement at scale.'],
      ['Social growth', 'Most-followed college club in DU. 10K+ followers in 6 months. 270%+ engagement boost via data-driven optimisation.'],
    ],
    statics: [
      [A('work/tds1.webp'), 'Tier 1 post', 'Audition Workshop'],
      [A('work/tds2.webp'), 'Creator collab', 'MostlySane'],
      [A('work/tds3.webp'), 'Flagship event', 'The Grand Open Mic'],
      [A('work/tds4.webp'), 'Panel reveal', 'Judges panel'],
    ],
    reels: [
      [A('work/tdsr1.webp'), 'Event pre-buzz', '28.2K', 'https://instagram.com/reel/DPQl2kmE-qq/'],
      [A('work/tdsr2.webp'), "Freshers' welcome", '25.4K', 'https://instagram.com/reel/DPatQBiEzfe/'],
      [A('work/tdsr3.webp'), '30-year legacy', '30.4K', 'https://instagram.com/reel/DPflCywE3rh/'],
      [A('work/tdsr4.webp'), 'Celebrity collab', '30.2K', 'https://instagram.com/reel/DP3Td-Nk63U/'],
      [A('work/tdsr5.webp'), 'Viral sketch', '471K', 'https://instagram.com/reel/DRY7Y8rkzaH/'],
      [A('work/tdsr6.webp'), 'Artist reveal', '451K', null],
    ],
  },
  {
    id: 'signal',
    no: '05',
    title: 'Signal',
    client: 'JioHotstar',
    logo: A('brand/hotstar.webp'),
    role: 'Marketing & GTM Strategy Lead',
    sub: 'JioHotstar show launch · 5–7 college campuses · 30,000+ Gen-Z target',
    tags: ['GTM', 'Campus Activation', 'Influencer Network', 'OTT'],
    stat: ['7L+', 'impressions'],
    theme: { bg: '#D8E0E8', fg: '#0A2BF5', accent: '#051024' },
    cover: A('work/hs3.webp'),
    problem: {
      kicker: 'The insight',
      head: "Gen-Z doesn't show up for ads. They show up for culture.",
      body: 'The challenge: make a streaming show launch feel like a campus moment — and then convert it.',
    },
    moves: [
      ['Audience architecture', 'Tiered segmentation across 5–7 campuses with hyper-personalised messaging at each touchpoint. <b>30,000+ students reached.</b>'],
      ['Micro-influencer network', 'Built and scaled 25–40 campus influencers to unlock organic reach and compress cost-per-reach vs paid. <b>45,000+ organic reach.</b>'],
      ['Celebrity amplification', 'Orchestrated campaigns featuring Abhishek Malhan & Khushboo Patani to spike live engagement and drive cultural credibility.'],
      ['UGC conversion engine', 'Turned on-ground attendees into content distributors — footfall into organic amplification. <b>8,000+ peer-to-peer shares.</b>'],
    ],
    gallery: [
      [A('work/hs6.webp'), 'Live activation — stage'],
      [A('work/hs3.webp'), 'Live activation — panel'],
      [A('work/hs5.webp'), 'Live activation — crowd'],
      [A('work/hs4.webp'), 'On-ground screening'],
    ],
    metrics: [
      ['7L+', 'Impressions', 'in 72 hours'],
      ['15%', 'Conversion rate', 'peak'],
      ['40K+', 'Engagements', 'total'],
      ['1.3K+', 'Attendees', 'converted'],
    ],
  },
];

// Insomniac work. `r` = height / width, `k` = filter key.
const G = (n, title, k, r) => ({ src: A(`gallery/${String(n).padStart(2, '0')}.webp`), title, k, r });
export const wallFilters = [
  ['all', 'Everything'],
  ['poster', 'Poster design'],
  ['social', 'Social media'],
  ['type', 'Typography'],
  ['grade', 'Colour grading'],
  ['gaming', 'Gaming & brand'],
];
export const wall = [
  G(1, 'Mischief Managed — identity', 'type', 1),
  G(2, 'Debunking Myths — Udaya, SRCC', 'social', 1),
  G(3, 'SafarNama — stand-up poster', 'poster', 1.25),
  G(4, 'Mumbai — colour grade', 'grade', 1.78),
  G(5, 'Win your CUET — promo post', 'social', 1.25),
  G(6, 'Normal-isation — board-game series', 'social', 1.25),
  G(7, 'Valentine Special — show poster', 'poster', 1.25),
  G(8, 'F*** Average — poster', 'type', 1.25),
  G(9, 'CUET Commerce 2026 — board game', 'social', 1.25),
  G(10, 'DU summer break — post', 'social', 1.25),
  G(11, 'Live classes — board-game series', 'social', 1.25),
  G(12, "Don't Overthink It — type study", 'type', 1.25),
  G(13, 'RNTL. — garment drop', 'gaming', 1.25),
  G(15, 'Live & fun — stream key art', 'gaming', 0.56),
  G(16, 'SafarNama, Kanpur — show poster', 'poster', 1.25),
  G(17, 'Histrionica — judges', 'poster', 1.25),
  G(18, 'Charades — stage play', 'poster', 1.25),
  G(19, 'Bellavita — fest campaign', 'gaming', 0.78),
  G(20, 'Solo 11 Kills — tournament', 'gaming', 0.56),
  G(21, 'Prajakta Koli — book launch', 'poster', 1.33),
  G(22, 'The off-duty drop', 'type', 1.25),
  G(23, 'The Final Hand — invitation', 'type', 1.41),
  G(24, 'Analytical questions — board-game series', 'social', 1.25),
  G(25, 'Paid internship — post', 'social', 1.25),
  G(27, "Still Rollin'", 'grade', 1.26),
  G(28, 'Logging into DU-gram', 'social', 1.25),
  G(29, 'Group chats — post', 'social', 1.25),
  G(30, 'Evocus × Dramsoc', 'gaming', 1.78),
  G(31, 'Priyanshu Modi — Histrionica standee', 'poster', 1.78),
  G(32, 'Coast — colour grade', 'grade', 1.25),
  G(33, 'Solo WWCD — grand finals', 'gaming', 0.56),
  G(34, 'Apollo shirt — rent at ₹450', 'gaming', 1.25),
  G(35, 'BizStreet ’25 — Shark Tank panel', 'poster', 1.25),
  G(36, 'Full closet? — RNTL.', 'gaming', 1.25),
  G(37, 'Night portrait', 'grade', 1.25),
  G(38, 'Pehla Kadam at SRCC', 'type', 1.78),
  G(39, 'Giveaway — Wings Phantom Pro', 'gaming', 1),
  G(40, 'Jamming Session — poster', 'poster', 1),
  G(41, 'Top Fella', 'type', 1.25),
  G(42, 'PlayStation — gaming partner', 'gaming', 1.25),
  G(43, 'Coast — alternate grade', 'grade', 1.25),
  G(44, 'Pyaar aur SSC — show poster', 'poster', 0.56),
  G(45, 'Time pressure — board-game series', 'social', 1.25),
  G(46, 'Deadline Extended — poster', 'poster', 1.78),
  G(47, 'Raah Warga', 'type', 1.26),
  G(48, 'Take That Chance', 'type', 1.25),
  G(49, 'Why buy when you can rent — RNTL.', 'type', 1.25),
  G(51, 'Audition Workshop — Dramsoc', 'poster', 1.25),
  G(52, 'Humble — gaming thumbnail', 'gaming', 0.56),
  G(53, 'Giveaway — EKSA headset', 'gaming', 1),
];
